import streamlit as st
import google.generativeai as genai
import json
import os
import requests
import io
from fpdf import FPDF
import PyPDF2

# ==========================================
# ⚙️ CONFIGURATION
# ==========================================
st.set_page_config(
    page_title="Contract Intelligence", 
    layout="wide", 
    page_icon="⚖️",
    initial_sidebar_state="expanded"
)

# ⚡ CORE ENGINE: Gemini 2.5 Pro (Best for Reasoning/Legal Analysis)
ACTIVE_MODEL = "gemini-2.5-pro"

# 1. CREDENTIALS
try:
    API_KEY = os.environ.get("GEMINI_API_KEY")
    if not API_KEY:
        API_KEY = st.secrets["GEMINI_API_KEY"]
except:
    API_KEY = None

DISCORD_WEBHOOK = os.environ.get("DISCORD_WEBHOOK_URL")
GUMROAD_PRODUCT_ID = "xGeemEFxpMJUbG-jUVxIHg==" 

# ==========================================
# 🧠 INTELLIGENCE SCHEMA & CONTEXT
# ==========================================

# 1. Analysis Contexts (The "Brain" triggers)
CONTRACT_DEFINITIONS = {
    "General / Universal": "Focus on Term, Termination, Payment, and General Liability.",
    "Drilling / Rig Contract": "Focus on Day Rates, NPT (Non-Productive Time), Pollution Liability, and Knock-for-Knock.",
    "EPC / Construction": "Focus on Milestones, Completion Guarantees, LDs (Liquidated Damages), and HSE.",
    "SaaS / Technology": "Focus on Data Privacy (HSE equivalent), Uptime SLAs (Performance), and IP Rights.",
    "Master Service Agreement (MSA)": "Focus on Call-Off mechanisms, Umbrella Liability, and Rate fixation.",
    "Technical Manpower": "Focus on Personnel qualification, Visa/Immigration compliance, and Replacement rights."
}

# 2. Output Schema
SCHEMA_DEF = """
{
  "contractDetails": {
    "title": "Official Title of Agreement",
    "parties": ["Party A", "Party B"]
  },
  "overallRisk": {
    "score": 0-100,
    "level": "High/Medium/Low",
    "rationale": "One sentence synthesis of the primary risk driver."
  },
  "keyCommercials": {
    "value": "Total Contract Value or Rate Structure",
    "duration": "Effective Date to End Date + Extensions",
    "contractType": "e.g. Drilling, EPC, MSA, SaaS"
  },
  "executiveSummary": [
    "- **Headline**: Brief synthesis of point 1.",
    "- **Headline**: Brief synthesis of point 2.",
    "- **Headline**: Brief synthesis of point 3."
  ],
  "riskMatrix": {
    "Liability & Indemnity": { "level": "High/Med/Low", "summary": "Caps, Knock-for-knock, Carve-outs." },
    "HSE & Operational": { "level": "High/Med/Low", "summary": "Safety criticals, Stop Work, Pollution." },
    "Termination & Exit": { "level": "High/Med/Low", "summary": "Convenience rights, fees, notice periods." },
    "Compliance & Governance": { "level": "High/Med/Low", "summary": "Anti-Bribery, Sanctions Clauses, Local Content requirements found in text." }
  },
  "scope": {
    "pricingModel": "Lumpsum / Unit Rate / Reimbursable",
    "paymentTerms": "e.g. Net 45 Days",
    "deliverables": "Key goods or services to be provided."
  },
  "detailedAnalysis": "Markdown string containing the full deep-dive report (Commercials, Scope, Legal, HSE, Recommendations) formatted with ## Headings and bullets."
}
"""

# ==========================================
# 📄 STYLISH PDF ENGINE (v1.0 Identity)
# ==========================================
class StrategicReport(FPDF):
    def header(self):
        # 1. Brand Colors
        self.navy = (0, 51, 102)
        self.grey = (100, 100, 100)
        
        # 2. Top Line
        self.set_font('Arial', 'B', 10)
        self.set_text_color(*self.grey)
        self.cell(0, 10, 'CONFIDENTIAL // CONTRACT INTELLIGENCE // v1.0', 0, 1, 'R')
        
        # 3. Divider
        self.set_draw_color(200, 200, 200) # Light Grey
        self.line(10, 20, 200, 20)
        self.ln(15)

    def footer(self):
        self.set_y(-15)
        self.set_font('Arial', 'I', 8)
        self.set_text_color(150, 150, 150)
        self.cell(0, 10, f'Page {self.page_no()} | Generated by Contract Intelligence | Legal Review Required', 0, 0, 'C')

    def chapter_title(self, label):
        self.set_font('Arial', 'B', 14)
        self.set_text_color(0, 51, 102) # Brand Navy
        self.cell(0, 10, label, 0, 1, 'L')
        
        # Underline
        self.set_draw_color(0, 51, 102)
        self.line(10, self.get_y(), 200, self.get_y())
        self.ln(8)

    def chapter_body(self, body):
        self.set_font('Arial', '', 11)
        self.set_text_color(50, 50, 50) # Dark Grey for readability
        
        # Markdown Parsing
        lines = body.split('\n')
        for line in lines:
            line = line.strip()
            if not line: continue
            
            if line.startswith('## '):
                self.ln(6)
                self.set_font('Arial', 'B', 12)
                self.set_text_color(0, 0, 0)
                self.cell(0, 8, line.replace('## ', '').strip(), 0, 1)
            elif line.startswith('- ') or line.startswith('* '):
                self.set_font('Arial', '', 11)
                self.set_text_color(50, 50, 50)
                self.set_x(15) # Indent
                self.multi_cell(0, 6, chr(149) + " " + line[2:].strip()) # Bullet
            else:
                self.set_font('Arial', '', 11)
                self.set_text_color(50, 50, 50)
                self.multi_cell(0, 6, line)
        self.ln(4)

def generate_pdf(data):
    pdf = StrategicReport()
    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=15)

    # 1. Title Section
    details = data.get('contractDetails', {})
    risk = data.get('overallRisk', {})
    comm = data.get('keyCommercials', {})
    
    pdf.set_font('Arial', 'B', 24)
    pdf.set_text_color(30, 30, 30)
    pdf.multi_cell(0, 10, "Strategic Contract Assessment", 0, 'L')
    pdf.ln(5)
    
    pdf.set_font('Arial', 'B', 12)
    pdf.set_text_color(100, 100, 100)
    pdf.multi_cell(0, 8, str(details.get('title', 'Contract Analysis')), 0, 'L')
    pdf.ln(10)

    # 2. The Verdict Box (Style Guide v1.0)
    # Background: Very Light Blue (#F0F5FF)
    pdf.set_fill_color(240, 245, 255) 
    # Border: Navy Blue
    pdf.set_draw_color(0, 51, 102) 
    pdf.rect(10, pdf.get_y(), 190, 50, 'FD')
    
    pdf.set_xy(15, pdf.get_y() + 5)
    
    # Verdict Title
    pdf.set_font('Arial', 'B', 12)
    pdf.set_text_color(0, 51, 102) # Navy
    score = risk.get('score', 0)
    level = risk.get('level', 'N/A').upper()
    pdf.cell(0, 8, f"STRATEGIC VERDICT: {level} RISK ({score}/100)", 0, 1)
    
    # Executive Summary Bullets
    pdf.set_font('Arial', '', 11)
    pdf.set_text_color(0, 0, 0)
    pdf.set_x(15)
    
    summary_text = ""
    for item in data.get('executiveSummary', []):
        clean_item = item.replace('**', '').replace('-', '').strip()
        summary_text += "- " + clean_item + "\n"
    
    pdf.multi_cell(180, 6, summary_text)
    pdf.ln(25)

    # 3. Commercial Snapshot
    pdf.chapter_title("1. Commercial Snapshot")
    pdf.set_font('Arial', 'B', 11)
    
    # Grid Layout for Commercials
    start_y = pdf.get_y()
    
    # Col 1: Type
    pdf.cell(60, 8, "Contract Type:", 0, 0)
    pdf.set_font('Arial', '', 11)
    pdf.cell(0, 8, str(comm.get('contractType')), 0, 1)
    
    # Col 2: Value
    pdf.set_font('Arial', 'B', 11)
    pdf.cell(60, 8, "Value Structure:", 0, 0)
    pdf.set_font('Arial', '', 11)
    pdf.cell(0, 8, str(comm.get('value')), 0, 1)
    
    # Col 3: Duration
    pdf.set_font('Arial', 'B', 11)
    pdf.cell(60, 8, "Duration:", 0, 0)
    pdf.set_font('Arial', '', 11)
    pdf.cell(0, 8, str(comm.get('duration')), 0, 1)
    pdf.ln(10)

    # 4. Detailed Analysis Body
    report_body = data.get('detailedAnalysis', "No detailed analysis generated.")
    pdf.chapter_body(report_body)

    return pdf.output(dest='S').encode('latin-1', 'replace')

# ==========================================
# 🛠️ UTILITIES
# ==========================================
def check_gumroad_license(key):
    if not key: return False, "Enter Key"
    url = "https://api.gumroad.com/v2/licenses/verify"
    params = {"product_id": GUMROAD_PRODUCT_ID, "license_key": key, "increment_uses_count": "false"}
    try:
        response = requests.post(url, data=params)
        data = response.json()
        if data.get("success") and not data.get("purchase", {}).get("refunded"): return True, "Valid"
        return False, "Invalid Key"
    except: return False, "Connection Error"

def log_to_discord(message):
    if DISCORD_WEBHOOK:
        try: requests.post(DISCORD_WEBHOOK, json={"content": message})
        except: pass

def extract_text(file_obj):
    try:
        reader = PyPDF2.PdfReader(file_obj)
        text = ""
        # 1.5 Pro has large context, reading up to 120 pages safely
        for i in range(min(len(reader.pages), 120)): 
            text += reader.pages[i].extract_text() + "\n"
        return text
    except: return None

# ==========================================
# 🧠 ANALYSIS ENGINE (Gemini 2.5 Pro)
# ==========================================
def run_analysis(text, contract_type, perspective):
    genai.configure(api_key=API_KEY)
    model = genai.GenerativeModel(ACTIVE_MODEL)
    
    # Context Injection
    specific_focus = CONTRACT_DEFINITIONS.get(contract_type, "General Commercial Analysis")
    
    # The Senior Strategist Prompt
    base_instruction = f"""
    YOU ARE A SENIOR LEGAL STRATEGIST AND PROCUREMENT MANAGER.
    
    **CONTEXT:**
    - **Contract Type:** {contract_type} ({specific_focus})
    - **Perspective:** You are acting for the **{perspective}**. Protect their interests aggressively.
    
    **TASK:** Analyze the provided contract and extract structured data for a management dashboard and a detailed written report.

    **STYLE GUIDE (McKinsey Style):**
    - **Synthesis over Summary**: Do not just repeat clauses; explain "So What?" and the business impact.
    - **Active Voice**: Use direct, punchy sentences.
    - **Data-Driven**: Extract numbers, caps, and dates explicitly.

    You must return a JSON object matching the provided schema.

    1. **Structured Data Fields**:
       - **contractDetails**: Official title and parties.
       - **overallRisk**: 'High'/'Medium'/'Low' based on {perspective}'s risk exposure.
       - **keyCommercials**: Value, duration, type.
       - **executiveSummary**: 3-5 high-impact bullet points. Use Markdown. Focus on Bottom Line Up Front.
       - **riskMatrix**: Analyze Liability, HSE, Termination, Compliance.
       - **scope**: Pricing model, payment terms, deliverables.

    2. **detailedAnalysis Field**:
       - A full deep-dive report in Markdown.
       - HEADINGS:
         - ## Commercial & Financial Profile
         - ## Scope of Work & Technical Review
         - ## Liquidated Damages and Service Credits
         - ## Liability, Indemnities, Insurance
         - ## HSE, Operational and Performance Risk
         - ## Term, Termination, Breach and Force Majeure
         - ## Legal, Compliance and Governance
         - ## Strategic Recommendations (Tailored for the {perspective})
    
    OUTPUT SCHEMA:
    {SCHEMA_DEF}
    
    CONTRACT TEXT:
    {text[:150000]}
    """
    
    try:
        response = model.generate_content(base_instruction, generation_config={"response_mime_type": "application/json"})
        return json.loads(response.text)
    except Exception as e:
        return {"error": str(e)}

# ==========================================
# 🖥️ UI / DASHBOARD
# ==========================================
def main():
    
    # --- UI STYLING ---
    st.markdown("""
        <style>
        .stApp { background-color: #ffffff; font-family: 'Helvetica Neue', sans-serif; }
        .metric-card {
            background-color: white; border: 1px solid #e5e7eb; border-radius: 8px;
            padding: 20px; box-shadow: 0 1px 2px 0 rgba(0,0,0,0.05);
            height: 100%; display: flex; flex-direction: column;
        }
        .card-label { font-size: 0.75rem; color: #6b7280; text-transform: uppercase; font-weight: 700; margin-bottom: 5px; }
        .card-value { font-size: 1.25rem; font-weight: 700; color: #111827; }
        .risk-badge { padding: 4px 10px; border-radius: 12px; font-size: 0.75rem; font-weight: 700; text-transform: uppercase; display: inline-block; }
        .bg-high { background-color: #fef2f2; color: #991b1b; border: 1px solid #fecaca; }
        .bg-med { background-color: #fffbeb; color: #92400e; border: 1px solid #fde68a; }
        .bg-low { background-color: #ecfdf5; color: #065f46; border: 1px solid #a7f3d0; }
        </style>
    """, unsafe_allow_html=True)

    # --- SIDEBAR ---
    with st.sidebar:
        st.markdown("### 🔐 Secure Login")
        if "authenticated" not in st.session_state: st.session_state.authenticated = False
        
        if not st.session_state.authenticated:
            key = st.text_input("License Key", type="password")
            if st.button("Authenticate"):
                valid, msg = check_gumroad_license(key)
                if valid:
                    st.session_state.authenticated = True
                    st.success("Access Granted")
                    st.rerun()
                else: st.error(msg)
            st.stop()
            
        st.success("🟢 System Online")
        
        # --- ANALYSIS PARAMETERS ---
        st.markdown("---")
        st.header("Analysis Parameters")
        
        # 1. Contract Type
        c_type = st.selectbox(
            "Contract Type",
            list(CONTRACT_DEFINITIONS.keys()),
            help="Select the specific domain to tailor the AI's analysis."
        )
        
        # 2. Perspective
        perspective = st.radio(
            "Perspective",
            ["Client / Buyer", "Contractor / Vendor"],
            help="The AI will protect the interests of the selected party."
        )
        
        st.markdown("---")
        uploaded_file = st.file_uploader("Upload Agreement (PDF)", type=["pdf"])
        
        if st.button("Logout"):
            st.session_state.authenticated = False
            st.rerun()

    # --- MAIN CONTENT ---
    c1, c2 = st.columns([3,1])
    with c1:
        st.markdown('### ⚙️ CONTRACT INTELLIGENCE', unsafe_allow_html=True)
        st.caption("Strategic Analysis & Procurement Guardrails (v1.0)")
    
    if uploaded_file:
        if st.button("🚀 Run Strategic Analysis"):
            with st.spinner("⚙️ Analyzing Commercials, Risk & Compliance..."):
                text = extract_text(uploaded_file)
                if text:
                    result = run_analysis(text, c_type, perspective)
                    if "error" not in result:
                        st.session_state.result = result
                        st.rerun()
                    else: st.error(f"Analysis Failed: {result['error']}")

    # --- DASHBOARD RENDER ---
    if "result" in st.session_state:
        data = st.session_state.result
        
        # 1. METADATA & RISK SCORE
        details = data.get('contractDetails', {})
        risk = data.get('overallRisk', {})
        comm = data.get('keyCommercials', {})
        
        st.markdown(f"## {details.get('title', 'Contract Assessment')} ✅")
        st.caption(f"Parties: {', '.join(details.get('parties', []))}")
        
        # Metric Row
        c1, c2, c3, c4 = st.columns(4)
        
        lvl = risk.get('level', 'Medium')
        bg_cls = "bg-high" if lvl == 'High' else "bg-med" if lvl == 'Medium' else "bg-low"
        
        with c1:
            st.markdown(f"""
            <div class="metric-card">
                <div class="card-label">Overall Risk</div>
                <div><span class="risk-badge {bg_cls}">{lvl}</span> <span style="font-size:1.2rem; font-weight:700;">{risk.get('score')}/100</span></div>
                <div style="font-size:0.8rem; color:#666; margin-top:5px;">{risk.get('rationale')}</div>
            </div>
            """, unsafe_allow_html=True)
            
        with c2: st.markdown(f'<div class="metric-card"><div class="card-label">Contract Value</div><div class="card-value">{comm.get("value")}</div></div>', unsafe_allow_html=True)
        with c3: st.markdown(f'<div class="metric-card"><div class="card-label">Duration</div><div class="card-value" style="font-size:1rem;">{comm.get("duration")}</div></div>', unsafe_allow_html=True)
        with c4: st.markdown(f'<div class="metric-card"><div class="card-label">Type</div><div class="card-value">{comm.get("contractType")}</div></div>', unsafe_allow_html=True)

        st.markdown("---")

        # 2. EXECUTIVE SUMMARY
        st.subheader("📝 Executive Synthesis")
        for item in data.get('executiveSummary', []):
            st.markdown(item)
            
        st.markdown("---")

        # 3. RISK MATRIX GRID
        st.subheader("🛡️ Risk & Compliance Matrix")
        r_grid = data.get('riskMatrix', {})
        
        rc1, rc2 = st.columns(2)
        
        def render_risk_box(title, obj):
            l = obj.get('level', 'Low')
            b = "bg-high" if l == 'High' else "bg-med" if l == 'Medium' else "bg-low"
            return f"""
            <div class="metric-card" style="margin-bottom:20px;">
                <div style="display:flex; justify-content:space-between;">
                    <span style="font-weight:700;">{title}</span>
                    <span class="risk-badge {b}">{l}</span>
                </div>
                <p style="font-size:0.9rem; margin-top:10px;">{obj.get('summary')}</p>
            </div>
            """

        with rc1:
            st.markdown(render_risk_box("Liability & Indemnity", r_grid.get('Liability & Indemnity', {})), unsafe_allow_html=True)
            st.markdown(render_risk_box("HSE & Operational", r_grid.get('HSE & Operational', {})), unsafe_allow_html=True)
            
        with rc2:
            st.markdown(render_risk_box("Termination & Exit", r_grid.get('Termination & Exit', {})), unsafe_allow_html=True)
            st.markdown(render_risk_box("Compliance & Governance", r_grid.get('Compliance & Governance', {})), unsafe_allow_html=True)

        # 4. DEEP DIVE REPORT
        st.markdown("### 📋 Detailed Strategic Report")
        with st.expander("View Full McKinsey-Style Analysis", expanded=True):
            st.markdown(data.get('detailedAnalysis', 'Report generation failed.'))

        # 5. PDF EXPORT
        st.markdown("---")
        if st.button("📄 Download Strategic Report (PDF)"):
            pdf_bytes = generate_pdf(data)
            st.download_button("📥 Click to Download", pdf_bytes, "Strategic_Report.pdf", "application/pdf")

if __name__ == "__main__":
    main()
