import streamlit as st
import google.generativeai as genai
import PyPDF2
import docx
from fpdf import FPDF
from io import StringIO
import datetime
import json
import time
import re
import pandas as pd
import os
import requests  # Required for Gumroad & Discord

# ==========================================
# ⚙️ CONFIGURATION & SECRETS
# ==========================================
ACTIVE_MODEL = "gemini-2.0-flash-exp"
APP_VERSION = "1.1.0"

# 1. API KEY (Gemini)
try:
    API_KEY = os.environ.get("GEMINI_API_KEY")
    if not API_KEY:
        API_KEY = st.secrets["GEMINI_API_KEY"]
except:
    API_KEY = "MISSING_KEY"

# 2. DISCORD WEBHOOK (The Watchtower)
# Add this to Render Environment Variables as 'DISCORD_WEBHOOK_URL'
DISCORD_WEBHOOK = os.environ.get("DISCORD_WEBHOOK_URL")

# 3. GUMROAD CONFIGURATION
# Replace this with your actual ID from the Gumroad "Content" tab
GUMROAD_PRODUCT_ID = "xGeemEFxpMJUbG-jUVxIHg==" 

# ==========================================
# 🛠️ HELPER FUNCTIONS
# ==========================================

def check_gumroad_license(key):
    """Verifies license validity, cancellation status, and refunds."""
    url = "https://api.gumroad.com/v2/licenses/verify"
    params = {
        "product_id": GUMROAD_PRODUCT_ID,
        "license_key": key,
        "increment_uses_count": "false"
    }
    
    try:
        response = requests.post(url, data=params)
        data = response.json()
        
        if not data.get("success"):
            return False, "❌ Invalid License Key."
            
        purchase = data.get("purchase", {})
        
        if purchase.get("refunded") or purchase.get("chargebacked"):
             return False, "⛔ Access denied: Purchase refunded."

        if purchase.get("subscription_cancelled_at"):
             return False, "⚠️ Subscription Cancelled. Reactivate to access."
             
        if purchase.get("subscription_failed_at"):
             return False, "⚠️ Payment Failed. Update billing info."

        return True, "✅ Access Granted"
        
    except Exception as e:
        return False, f"Connection Error: {str(e)}"

def log_usage(license_key, filename, file_size):
    """Sends a ping to Discord when a contract is analyzed."""
    if not DISCORD_WEBHOOK: return
    
    masked_key = f"****{license_key[-4:]}" if len(license_key) > 4 else "Unknown"
    timestamp = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    size_mb = round(file_size / (1024 * 1024), 2)
    
    message = {
        "content": f"🚨 **Analysis Run**\n"
                   f"👤 **User:** `{masked_key}`\n"
                   f"📄 **File:** `{filename}` ({size_mb} MB)\n"
                   f"⏰ **Time:** {timestamp}"
    }
    try:
        requests.post(DISCORD_WEBHOOK, json=message)
    except:
        pass

def extract_json(text):
    """Surgical extractor to find JSON within AI chatter."""
    text = text.replace("```json", "").replace("```", "")
    text = re.sub(r'[\\x00-\\x1f\\x7f]', '', text) 
    try:
        start = text.find('{')
        end = text.rfind('}') + 1
        if start != -1 and end != -1:
            return json.loads(text[start:end])
        return None
    except: return None

def safe_get(data, path, default="N/A"):
    try:
        current = data
        for key in path:
            if isinstance(current, list):
                if len(current) > 0: current = current[0]
                else: return default
            elif isinstance(current, dict):
                current = current.get(key, default)
            else:
                return default
        return current
    except:
        return default

def clean_text(text):
    if not isinstance(text, str): return str(text)
    replacements = {"’": "'", "‘": "'", "“": '"', "”": '"', "–": "-", "—": "-", "…": "..."}
    for char, replacement in replacements.items():
        text = text.replace(char, replacement)
    return text.encode('latin-1', 'ignore').decode('latin-1')

# ==========================================
# 📄 PDF ENGINE
# ==========================================
class StrategicReport(FPDF):
    def header(self):
        self.set_font('Helvetica', 'B', 10)
        self.set_text_color(80, 80, 80)
        self.cell(0, 10, f'CONFIDENTIAL // STRATEGIC ASSESSMENT // v{APP_VERSION}', 0, 1, 'L')
        self.line(10, 20, 200, 20)
        self.ln(10)
    def footer(self):
        self.set_y(-15)
        self.set_font('Helvetica', 'I', 8)
        self.set_text_color(150, 150, 150)
        self.cell(0, 10, f'Generated by Strategic Contract Assessment AI - Page {self.page_no()}', 0, 0, 'C')

def create_pdf(data):
    pdf = StrategicReport()
    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=15)
    
    # Title
    pdf.set_font("Helvetica", "B", 18)
    pdf.set_text_color(0, 0, 0)
    title = safe_get(data, ['contractDetails', 'title'], 'Contract Analysis')
    pdf.multi_cell(0, 8, clean_text(title), 0, 'L')
    pdf.ln(5)
    
    # Score
    pdf.set_font("Helvetica", "", 10)
    score = safe_get(data, ['riskScore', 'score'])
    pdf.cell(0, 8, f"Date: {datetime.date.today()} | Risk Score: {score}/100", 0, 1, 'L')
    pdf.ln(5)
    
    # Exec Summary
    pdf.set_fill_color(240, 240, 240)
    pdf.set_font("Helvetica", "B", 12)
    pdf.cell(0, 10, "1. EXECUTIVE SYNTHESIS", 0, 1, 'L', fill=True)
    pdf.ln(3)
    pdf.set_font("Helvetica", "", 10)
    summary = safe_get(data, ['executiveSummary'], 'No summary available.')
    pdf.multi_cell(0, 6, clean_text(summary))
    pdf.ln(5)

    # Vendor Intel
    pdf.set_font("Helvetica", "B", 12)
    pdf.cell(0, 10, "2. VENDOR INTELLIGENCE", 0, 1, 'L', fill=True)
    pdf.ln(3)
    pdf.set_font("Helvetica", "B", 10)
    pdf.cell(40, 6, "Entity:", 0, 0)
    pdf.set_font("Helvetica", "", 10)
    pdf.cell(0, 6, clean_text(safe_get(data, ['compliance', 'entity'])), 0, 1)
    pdf.set_font("Helvetica", "B", 10)
    pdf.cell(40, 6, "Sanctions:", 0, 0)
    pdf.set_font("Helvetica", "", 10)
    pdf.cell(0, 6, clean_text(safe_get(data, ['compliance', 'sanctions', 'status'])), 0, 1)
    pdf.ln(2)
    pdf.multi_cell(0, 6, clean_text(safe_get(data, ['compliance', 'sanctions', 'details'])))
    pdf.ln(5)

    # Risk Table
    pdf.set_font("Helvetica", "B", 12)
    pdf.cell(0, 10, "3. KEY RISK VECTORS", 0, 1, 'L', fill=True)
    pdf.ln(3)
    risks = safe_get(data, ['riskTable'], [])
    for item in risks:
        pdf.set_font("Helvetica", "B", 10)
        area = clean_text(item.get('area', 'Risk'))
        risk_level = clean_text(item.get('risk', '-'))
        pdf.cell(0, 6, f"{area} ({risk_level})", 0, 1)
        pdf.set_font("Helvetica", "", 10)
        pdf.multi_cell(0, 6, clean_text(item.get('finding', '')))
        pdf.ln(3)
        
    # Deep Dive
    pdf.add_page()
    pdf.set_font("Helvetica", "B", 12)
    pdf.cell(0, 10, "4. DETAILED DEEP DIVE ANALYSIS", 0, 1, 'L', fill=True)
    pdf.ln(5)
    pdf.set_font("Helvetica", "", 10)
    deep_dive = safe_get(data, ['deepDive'], 'No detailed analysis provided.')
    deep_dive_clean = clean_text(deep_dive.replace("##", "").replace("**", ""))
    pdf.multi_cell(0, 6, deep_dive_clean)

    return pdf.output(dest='S').encode('latin-1', 'replace')

# ==========================================
# 🧠 AI ENGINE (PROMPTS)
# ==========================================
BASE_INSTRUCTION = """
You are Contract Engine, a Senior Contract Analyst for an Oil & Gas Major.
Analyze the contract text and return ONLY a raw JSON object.

EXTRACTION RULES:
1. Commercials: If Schedule of Rates/Unit Rate, value must be "Schedule of Rates".
2. Duration: Extract exact dates and extension options (e.g. "3 Years (Jan 2022 - Dec 2024) + 1 Year Option").
3. Vendor Intel: Use internal knowledge to assess Counterparty (Sanctions, Financials).
4. Deep Dive: Provide detailed markdown report.

JSON SCHEMA:
{
  "contractDetails": { "title": "string", "parties": ["string"] },
  "riskScore": { "score": 0-100, "level": "High/Medium/Low" },
  "executiveSummary": "Markdown bullet points (BLUF).",
  "commercials": { "value": "string", "duration": "string" },
  "compliance": {
      "entity": "string",
      "sanctions": { "status": "Clean/Flagged", "details": "string" },
      "financial": { "status": "Stable/Unstable", "details": "string" }
  },
  "riskTable": [
      { "area": "Liability", "risk": "High/Med/Low", "finding": "string" },
      { "area": "Termination", "risk": "High/Med/Low", "finding": "string" },
      { "area": "Indemnity", "risk": "High/Med/Low", "finding": "string" }
  ],
  "deepDive": "Long-form Markdown string with headers (##) and bullets."
}
"""

COACH_INSTRUCTION = """
You are a Negotiation Coach. 
1. Explain the risk.
2. Draft a redline.
3. Provide a negotiation argument.
"""

def process_file(uploaded_file):
    try:
        if "pdf" in uploaded_file.type:
            reader = PyPDF2.PdfReader(uploaded_file)
            text = ""
            for page in reader.pages: text += page.extract_text()
            return text
        elif "word" in uploaded_file.type:
            doc = docx.Document(uploaded_file)
            text = "\\n".join([p.text for p in doc.paragraphs])
            return text
        elif "text" in uploaded_file.type:
            return StringIO(uploaded_file.getvalue().decode("utf-8")).read()
        return None
    except: return None

def analyze_contract(text, filename="Unknown", file_size=0, license_key="Unknown"):
    if not API_KEY or API_KEY == "MISSING_KEY":
        st.error("⚠️ System Error: API Key missing.")
        return None
        
    # 1. Log to Discord
    log_usage(license_key, filename, file_size)
    
    genai.configure(api_key=API_KEY)
    model = genai.GenerativeModel(ACTIVE_MODEL)
    try:
        # 2. Limit Token Output for Cost Control
        config = genai.types.GenerationConfig(
            response_mime_type="application/json", 
            temperature=0.0,
            max_output_tokens=2500 
        )
        response = model.generate_content(
            f"{BASE_INSTRUCTION}\\n\\nDATA:\\n{text}", 
            generation_config=config
        )
        return response.text
    except Exception as e:
        return None

# ==========================================
# 🖥️ MAIN UI
# ==========================================
def main():
    st.set_page_config(page_title="Strategic Contract Assessment", layout="wide", page_icon="🛡️")
    st.markdown("""
        <style>
        .stApp { background-color: #f8fafc; font-family: 'Inter', sans-serif; }
        #MainMenu {visibility: hidden;} footer {visibility: hidden;}
        [data-testid="stFileUploader"] small { display: none !important; color: transparent !important; }
        h1, h2, h3 { color: #0f172a; font-weight: 700; letter-spacing: -0.5px; }
        .metric-card { background-color: white; border: 1px solid #e2e8f0; border-radius: 12px; padding: 20px; box-shadow: 0 4px 6px -1px rgba(0, 0, 0, 0.1); text-align: center; }
        .metric-label { color: #64748b; font-size: 0.8rem; font-weight: 600; text-transform: uppercase; letter-spacing: 1px; }
        .metric-value { color: #0f172a; font-size: 1.5rem; font-weight: 700; }
        div.stButton > button { background-color: #2563eb; color: white; border-radius: 8px; font-weight: 600; border: none; width: 100%; }
        div.stButton > button:hover { background-color: #1d4ed8; }
        </style>
    """, unsafe_allow_html=True)

    # --- LICENSE GATE STATE ---
    if 'license_verified' not in st.session_state:
        st.session_state.license_verified = False
    if 'license_key' not in st.session_state:
        st.session_state.license_key = ""

    # --- SIDEBAR ---
    with st.sidebar:
        st.title("🛡️ Secure Portal")
        st.markdown("**Strategic Contract Assessment**")
        st.caption(f"v{APP_VERSION}") # Removed TLS 1.3
        st.markdown("---")

        if not st.session_state.license_verified:
            st.warning("🔒 Login Required")
            entered_key = st.text_input("Enter License Key", type="password")
            if st.button("Verify License"):
                valid, msg = check_gumroad_license(entered_key)
                if valid:
                    st.session_state.license_verified = True
                    st.session_state.license_key = entered_key
                    st.success(msg)
                    st.rerun()
                else:
                    st.error(msg)
            st.markdown("---")
            st.info("No key? Purchase access via Gumroad.")
            st.stop()
        else:
            st.success("✅ License Active")
            if st.button("Logout"):
                st.session_state.license_verified = False
                st.session_state.license_key = ""
                st.rerun()
            st.markdown("---")

        uploaded_file = st.file_uploader("Upload Agreement", type=["pdf", "docx", "txt"])
        if uploaded_file and uploaded_file.size > 30 * 1024 * 1024:
            st.error("File exceeds 30MB limit.")
            uploaded_file = None
        
        if uploaded_file: st.success("✅ Encrypted & Buffered")

    # --- MAIN CONTENT ---
    st.markdown("## Strategic Contract Assessment")
    st.markdown("##### ⚡ Oil & Gas Specialist Edition")
    st.markdown("---")

    if uploaded_file:
        if "file_data" not in st.session_state:
            with st.spinner("Processing document structure..."):
                text = process_file(uploaded_file)
                if text: st.session_state.file_data = text
                else: st.error("Corrupt or unreadable file."); st.stop()

        if st.button("Initialize Strategic Analysis"):
            progress = st.progress(0)
            status_text = st.empty()
            status_text.text("🔄 Establishing secure uplink to Neural Engine...")
            time.sleep(0.5); progress.progress(25)
            status_text.text("🧠 Analyzing commercial terms and deep dive vectors...")
            
            # CALL ANALYSIS WITH LOGGING
            raw_response = analyze_contract(
                st.session_state.file_data,
                filename=uploaded_file.name,
                file_size=uploaded_file.size,
                license_key=st.session_state.license_key
            )
            progress.progress(75)
            
            if raw_response:
                status_text.text("✨ Synthesizing Executive Report...")
                data_dict = extract_json(raw_response)
                
                if data_dict:
                    st.session_state.analysis = data_dict
                    progress.progress(100); time.sleep(0.5); st.rerun()
                else:
                    st.error("Data parsing error. The AI returned an invalid format.")
            else: 
                st.error("Analysis timed out. Please try again.")

    # --- RESULTS DASHBOARD ---
    if "analysis" in st.session_state:
        data = st.session_state.analysis
        c1, c2, c3 = st.columns(3)
        score = safe_get(data, ['riskScore', 'score'], 0)
        level = safe_get(data, ['riskScore', 'level'], 'Unknown')
        color = "#10b981"
        try:
            if int(score) > 70: color = "#ef4444" 
            elif int(score) > 40: color = "#f59e0b"
        except: pass
        
        with c1: st.markdown(f"<div class='metric-card'><div class='metric-label'>Risk Index</div><div class='metric-value' style='color: {color};'>{score}/100</div><small>{level}</small></div>", unsafe_allow_html=True)
        with c2: st.markdown(f"<div class='metric-card'><div class='metric-label'>Total Value</div><div class='metric-value' style='font-size: 1.2rem;'>{safe_get(data, ['commercials', 'value'])}</div></div>", unsafe_allow_html=True)
        with c3: st.markdown(f"<div class='metric-card'><div class='metric-label'>Duration</div><div class='metric-value' style='font-size: 1.2rem;'>{safe_get(data, ['commercials', 'duration'])}</div></div>", unsafe_allow_html=True)

        st.markdown("---")
        t1, t2, t3 = st.tabs(["📄 Strategic Dashboard", "📚 Deep Dive Analysis", "💬 Negotiation Coach"])
        
        with t1:
            st.info(f"**Vendor Intelligence:** {safe_get(data, ['compliance', 'entity'])}")
            vc1, vc2 = st.columns(2)
            vc1.write(f"**Sanctions:** {safe_get(data, ['compliance', 'sanctions', 'status'])}")
            vc2.write(f"**Financial:** {safe_get(data, ['compliance', 'financial', 'status'])}")
            st.caption(safe_get(data, ['compliance', 'sanctions', 'details']))
            st.divider()
            st.subheader("Executive Synthesis")
            st.markdown(safe_get(data, ['executiveSummary']))
            st.subheader("Key Risk Vectors")
            risks = safe_get(data, ['riskTable'], [])
            if isinstance(risks, list) and len(risks) > 0: st.dataframe(pd.DataFrame(risks), use_container_width=True, hide_index=True)
            st.markdown("---")
            pdf_bytes = create_pdf(data)
            st.download_button("📥 Download Official PDF Report", pdf_bytes, "Assessment.pdf", "application/pdf")

        with t2:
            st.subheader("Comprehensive Contract Deep Dive")
            st.markdown("Detailed breakdown of all contractual obligations and liabilities.")
            st.divider()
            st.markdown(safe_get(data, ['deepDive'], "Detailed analysis was not generated."))

        with t3:
            st.subheader("🤖 AI Negotiation Coach")
            st.caption("Ask me to redraft clauses or explain legal jargon.")
            if "messages" not in st.session_state: st.session_state.messages = []
            for msg in st.session_state.messages:
                with st.chat_message(msg["role"]): st.markdown(msg["content"])
            if prompt := st.chat_input("Ex: 'Redraft the indemnity clause'"):
                st.session_state.messages.append({"role": "user", "content": prompt})
                with st.chat_message("user"): st.markdown(prompt)
                with st.chat_message("assistant"):
                    with st.spinner("Drafting strategy..."):
                        genai.configure(api_key=API_KEY)
                        chat_model = genai.GenerativeModel(ACTIVE_MODEL, system_instruction=COACH_INSTRUCTION)
                        full_prompt = f"Contract Context: {st.session_state.file_data[:10000]}\\n\\nUser Question: {prompt}"
                        response = chat_model.generate_content(full_prompt)
                        st.markdown(response.text)
                        st.session_state.messages.append({"role": "assistant", "content": response.text})

if __name__ == "__main__":
    main()
